### ISSUE TITLE
Value changes observable

### ISSUE THREAD

**Issue by hoangbtmrk** [instance-oom/ngx-markdown-editor#140]
Hi dev team!
Could you support value changes that return value observable (like the function valueChanges of form control? I want this for implement auto save after debounce time duration. Many thanks

<img width="754" alt="Screen Shot 2023-08-21 at 11 22 30" src="https://github.com/instance-oom/ngx-markdown-editor/assets/110799121/5208eb70-1761-4e5e-a949-f9c6bc65541a">

**Comment by instance-oom** [comment]
Please use version `5.3.3`. This version has been exposed the `valueChanges` observable.
