### ISSUE TITLE
Custom font family

### ISSUE THREAD

**Issue by hoangbtmrk** [instance-oom/ngx-markdown-editor#142]
Hi dev team!
How can I update font family of text editor, I tried to use other font family, but the cursor will display wrong place, could you help me update it?

![Screen Shot 2023-09-06 at 14 39 48](https://github.com/instance-oom/ngx-markdown-editor/assets/110799121/a5f89db5-56d3-401e-9689-5bfa9728d038)

**Comment by instance-oom** [comment]
```ts
onEditorLoaded(editor) {
    editor.setOptions({
      fontFamily: "your custom font family"
    });
}
```

**Comment by hoangbtmrk** [comment]
Many thanks @instance-oom!

**Comment by hoangbtmrk** [comment]
@instance-oom 
The font family is applied, but the cursor position is wrong, you can see the above screenshot

**Comment by instance-oom** [comment]
Sorry too late. I think this is an ace editor's bug
