### ISSUE TITLE
Apply font color to list  in ngx markdown

### ISSUE THREAD

**Issue by Ramyaa675** [instance-oom/ngx-markdown-editor#143]
Background color is not getting applied for which is specified in span.
color is getting applied to only first line and its not getting applied to full text.
![image](https://github.com/instance-oom/ngx-markdown-editor/assets/14086231/2e9c3222-2320-40aa-b204-1e06a5582cc6)

**Comment by instance-oom** [comment]
Did you find the wrong repo?

This repo is 'ngx-markdown-editor' not 'ngx-markdown'
